### ISSUE TITLE
qifqif misinterprets qif file contents as unicode

### ISSUE THREAD

**Issue by jrrk** [Kraymer/qifqif#19]
Traceback (most recent call last):
  File "/usr/local/bin/qifqif", line 9, in <module>
    load_entry_point('qifqif==0.3.1', 'console_scripts', 'qifqif')()
  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 245, in main
    transacs = process_file(transacs_orig, options=args)
  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 109, in process_file
    options)
  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 96, in process_transaction
    match = query_match(cached_match, t['payee'])
  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 65, in query_match
    term.red('<none>')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 15: ordinal not in range(128)

**Comment by Kraymer** [comment]
Can you attach to the issue an (anonymized) excerpt --only the transaction block that fails-- of the file please?

**Comment by jrrk** [comment]
downstairs-study:Banking jrrk$ qifqif InformeA.qif

Amount..: -14.00

Payee...: PURCHASE - DOMESTIC, CAMBRIDGE, MARKS & SPENCER

Memo....: ** 1101

Category: clothing

Match: MARKS & SPENCER

Traceback (most recent call last):

  File "/usr/local/bin/qifqif", line 9, in <module>

    load_entry_point('qifqif==0.3.1', 'console_scripts', 'qifqif')()

  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 245, in main

    transacs = process_file(transacs_orig, options=args)

  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 109, in process_file

    options)

  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 96, in process_transaction

    match = query_match(cached_match, t['payee'])

  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 65, in query_match

    term.red('<none>')))

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 15: ordinal not in range(128)

downstairs-study:Banking jrrk$

**Comment by jrrk** [comment]
downstairs-study:Banking jrrk$ qifqif InformeA.qif
Amount..: -14.00
Payee...: PURCHASE - DOMESTIC, CAMBRIDGE, MARKS & SPENCER
Memo....: ** 1101
Category: clothing
Match: MARKS
Traceback (most recent call last):
  File "/usr/local/bin/qifqif", line 9, in <module>
    load_entry_point('qifqif==0.3.1', 'console_scripts', 'qifqif')()
  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 245, in main
    transacs = process_file(transacs_orig, options=args)
  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 109, in process_file
    options)
  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 96, in process_transaction
    match = query_match(cached_match, t['payee'])
  File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 65, in query_match
    term.red('<none>')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 15: ordinal not in range(128)
downstairs-study:Banking jrrk$ cat InformeA.qif 
!Type:CCard
D29/11/2014
T-14.00
PPURCHASE - DOMESTIC, CAMBRIDGE, MARKS & SPENCER
M** 1101
^
downstairs-study:Banking jrrk$

**Comment by Kraymer** [comment]
Can you grab the last sources see if d4d8c3b0f fixed it?
It now assumes utf-8 but should ignore chars it cannot handle instead of throwing.

**Comment by jrrk** [comment]
The error message from the new version has changed, but seems to mean the same.
The lack of a change to version number is suspect.
This is the procedure I followed:

git clone https://github.com/Kraymer/qifqif.git
cd qifqif/
git checkout  d4d8c3b
python setup.py build
python setup.py install
pushd
downstairs-study:Banking jrrk$ qifqif InformeA.qif
Amount..: -14.00
Payee...: PURCHASE - DOMESTIC, CAMBRIDGE, MARKS & SPENCER
Memo....: ** 1101
Category: clothing
Match: MARKS
Traceback (most recent call last):
  File "/usr/local/bin/qifqif", line 9, in <module>
    load_entry_point('qifqif==0.3.1', 'console_scripts', 'qifqif')()
  File "build/bdist.macosx-10.9-x86_64/egg/qifqif/__init__.py", line 246, in main
  File "build/bdist.macosx-10.9-x86_64/egg/qifqif/__init__.py", line 110, in process_file
  File "build/bdist.macosx-10.9-x86_64/egg/qifqif/__init__.py", line 97, in process_transaction
  File "build/bdist.macosx-10.9-x86_64/egg/qifqif/__init__.py", line 66, in query_match
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 15: ordinal not in range(128)
downstairs-study:Banking jrrk$

**Comment by Kraymer** [comment]
Hmm that's not exactly that : you need to launch the command from the cloned repository instead of the installed `qifqif`. Procedure :   

    git clone https://github.com/Kraymer/qifqif.git
    cd qifqif/
    python ./qifqif.py your_file.qif

**Comment by jrrk** [comment]
That procedure gives identical results apart from the path details, and possibly useful debugging:

downstairs-study:Downloads jrrk$ rm -rf qifqif/
downstairs-study:Downloads jrrk$ git clone https://github.com/Kraymer/qifqif.git
Cloning into 'qifqif'...
remote: Counting objects: 474, done.
remote: Total 474 (delta 0), reused 0 (delta 0), pack-reused 474
Receiving objects: 100% (474/474), 664.11 KiB | 0 bytes/s, done.
Resolving deltas: 100% (234/234), done.
Checking connectivity... done.
downstairs-study:Downloads jrrk$ cd qifqif/
downstairs-study:qifqif jrrk$ python ./qifqif.py ~/Documents/journaladd/Banking/InformeA.qif 
Amount..: -14.00
Payee...: PURCHASE - DOMESTIC, CAMBRIDGE, MARKS & SPENCER
Memo....: ** 1101
Category: clothing
Match: MARKS
Traceback (most recent call last):
  File "./qifqif.py", line 11, in <module>
    qifqif.main()
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 246, in main
    transacs = process_file(transacs_orig, options=args)
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 110, in process_file
    options)
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 97, in process_transaction
    match = query_match(cached_match, t['payee'])
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 66, in query_match
    term.red('<none>')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 15: ordinal not in range(128)

**Comment by Kraymer** [comment]
can you retry now? should be fixed by bffa38

    cd qifqif/
    git pull origin
    python ./qifqif.py your_file.qif

**Comment by jrrk** [comment]
The error has changed slightly, and the line numbers, not sure why you do not reproduce my result.

python qifqif.py ~/Documents/journaladd/Banking/InformeA.qif 
Amount..: -14.00
Payee...: PURCHASE - DOMESTIC, CAMBRIDGE, MARKS & SPENCER
Memo....: ** 1101
Category: clothing
Match: MARKS
Traceback (most recent call last):
  File "qifqif.py", line 11, in <module>
    qifqif.main()
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 248, in main
    transacs = process_file(transacs_orig, options=args)
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 112, in process_file
    options)
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 99, in process_transaction
    match = query_match(cached_match, t['payee'])
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 68, in query_match
    term.red('<none>')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 15: ordinal not in range(128)
downstairs-study:qifqif jrrk$ more !$
more ~/Documents/journaladd/Banking/InformeA.qif
!Type:CCard
D29/11/2014
T-14.00
PPURCHASE - DOMESTIC, CAMBRIDGE, MARKS & SPENCER
M** 1101
^
downstairs-study:qifqif jrrk$

**Comment by Kraymer** [comment]
Can you paste the result of typing in a terminal :  

    echo $LC_CTYPE
    echo $LANG

that will help me reproduce it

**Comment by jrrk** [comment]
downstairs-study:qifqif jrrk$ echo $LC_CTYPE
C
downstairs-study:qifqif jrrk$ echo $LANG
C

**Comment by Kraymer** [comment]
Well, I'm puzzled.
I saved the content you gave in a file *InformeA.qif* with utf-8 encoding.

    flap on master* ± echo $LC_CTYPE
    C
    flap on master* ± echo $LANG
    C
    flap on master* ± python ./qifqif.py InformeA.qif
    Amount..: -14.00
    Payee...: PURCHASE - DOMESTIC, CAMBRIDGE, MARKS & SPENCER
    Memo....: ** 1101
    Category: clothing
    Match: MARKS
    ✔ Match accepted: MARKS

If you want to pursue investigating here are some questions :  

- have you same problem with terminal using utf-8?

        export LANG=fr_FR.  
        export LC_CTYPE=fr_FR.UTF-8

- is it this specific transaction match that fails or any. Has it ever work with another .qif file maybe?
- is your .qif file in utf-8 encoding (should not be related)

Thanks for your patience. Heh you're the first user (aside me) to report something , so I make it last :clock1: :wink:

**Comment by jrrk** [comment]
It might be an idea to choose the locale in the preferences file. It's possible others could have the same problem.

downstairs-study:qifqif jrrk$ export LANG=fr_FR. 
downstairs-study:qifqif jrrk$ export LC_CTYPE=fr_FR.UTF-8
downstairs-study:qifqif jrrk$ python ./qifqif.py ~/Documents/journaladd/Banking/InformeA.qif
Traceback (most recent call last):
  File "./qifqif.py", line 8, in <module>
    import qifqif
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 24, in <module>
    term = Terminal()
  File "/usr/local/lib/python2.7/site-packages/blessed/terminal.py", line 222, in __init__
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

downstairs-study:qifqif jrrk$ export LANG=fr_FR
downstairs-study:qifqif jrrk$ export LC_CTYPE=fr_FR.UTF-8
downstairs-study:qifqif jrrk$ python ./qifqif.py ~/Documents/journaladd/Banking/InformeA.qif
Amount..: -14.00
Payee...: PURCHASE - DOMESTIC, CAMBRIDGE, MARKS & SPENCER
Memo....: ** 1101
Category: clothing
---
downstairs-study:qifqif jrrk$ 

downstairs-study:qifqif jrrk$ export LC_CTYPE=en_GB.UTF-8
downstairs-study:qifqif jrrk$ export LANG=en_GB
downstairs-study:qifqif jrrk$ python ./qifqif.py ~/Documents/journaladd/Banking/InformeA.qif
Amount..: -14.00
Payee...: PURCHASE - DOMESTIC, CAMBRIDGE, MARKS & SPENCER
Memo....: ** 1101
Category: clothing
---
downstairs-study:qifqif jrrk$

**Comment by Kraymer** [comment]
> It might be an idea to choose the locale in the preferences file. It's possible others could have the same problem.

Yep, but ideally qifqif should be able to handle any terminal encoding (without requiring a specific locale). Not clear why ``C`` locale failed in your case and not mine.
