### ISSUE TITLE
Crash when bad match entered

### ISSUE THREAD

**Issue by Kraymer** [Kraymer/qifqif#41]
STR: enter a string that doesn't figure in payee field

    Traceback (most recent call last):
      File "/usr/local/bin/qifqif", line 9, in <module>
        load_entry_point('qifqif==0.5.1', 'console_scripts', 'qifqif')()
      File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 350, in main
        transacs = process_file(transacs_orig, options=args)
      File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 237, in process_file
        cat, match = process_transaction(t, options)
      File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 224, in process_transaction
        ruler = query_ruler(t)
      File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 164, in query_ruler
        ok, extras = check_ruler(ruler, t)
      File "/usr/local/lib/python2.7/site-packages/qifqif/__init__.py", line 136, in check_ruler
        extras[field_ko] = TERM.red('✖ %s' % field_ko.title())
    AttributeError: 'dict' object has no attribute 'title'

**Comment by flywire** [comment]
Same here with new install running under Win7-32:

F:\QifQif-Test\QIFQIF~2>qifqif TransactionHistory-2.qif
Traceback (most recent call last):
  File "C:\Python27\Scripts\qifqif-script.py", line 9, in <module>
    load_entry_point('qifqif==0.5.1', 'console_scripts', 'qifqif')()
  File "C:\Python27\lib\site-packages\qifqif\__init__.py", line 350, in main
    transacs = process_file(transacs_orig, options=args)
  File "C:\Python27\lib\site-packages\qifqif\__init__.py", line 237, in process_file
    cat, match = process_transaction(t, options)
  File "C:\Python27\lib\site-packages\qifqif\__init__.py", line 207, in process_transaction
    print('---\n' + TERM.clear_eol, end='')
TypeError: coercing to Unicode: need string or buffer, function found

**Comment by Kraymer** [comment]
thanks for the report @flywire , it is in fact another bug, please follow its resolution at https://github.com/Kraymer/qifqif/issues/42

**Comment by flywire** [comment]
V0.6.0 works no problem.
