### ISSUE TITLE
blessed terminal functions are not properly emulated causing crash

### ISSUE THREAD

**Issue by Kraymer** [Kraymer/qifqif#42]
Traceback (most recent call last):
    File "C:\Python27\Scripts\qifqif-script.py", line 9, in 
    load_entry_point('qifqif==0.5.1', 'console_scripts', 'qifqif')()
    File "C:\Python27\lib\site-packages\qifqif__init__.py", line 350, in main
    transacs = process_file(transacs_orig, options=args)
    File "C:\Python27\lib\site-packages\qifqif__init__.py", line 237, in process_file
    cat, match = process_transaction(t, options)
    File "C:\Python27\lib\site-packages\qifqif__init__.py", line 207, in process_transaction
    print('---\n' + TERM.clear_eol, end='')
    TypeError: coercing to Unicode: need string or buffer, function found

**Comment by flywire** [comment]
V0.6.0 works no problem.
