### ISSUE TITLE
Crash after "any field" input mode passed

### ISSUE THREAD

**Issue by Kraymer** [Kraymer/qifqif#74]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/qifqif", line 9, in <module>
    load_entry_point('qifqif==0.7.0', 'console_scripts', 'qifqif')()
  File "build/bdist.macosx-10.6-intel/egg/qifqif/__init__.py", line 294, in main
  File "build/bdist.macosx-10.6-intel/egg/qifqif/__init__.py", line 272, in process_transactions
  File "build/bdist.macosx-10.6-intel/egg/qifqif/tags.py", line 130, in edit
AttributeError: 'dict' object has no attribute 'isspace'
```

**Comment by Kraymer** [comment]
Fixed by `cd6fe76`
