### ISSUE TITLE
Unable to install qifqif on macOs 

### ISSUE THREAD

**Issue by clombion** [Kraymer/qifqif#81]
**OS**: macOs 10.12.6
**CLI**: iTerm2
**Software**: Python 3.6 | pip 9.0.1
**Install process**: load Conda virtual environment > pip install qifqif
**error log**: 

```
Collecting qifqif
  Using cached qifqif-0.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kk/y3f49kbs3ps6rm04gb6qktv00000gn/T/pip-build-8i5itbya/qifqif/setup.py", line 43, in <module>
        long_description=coerce_file('README.md'),
      File "/private/var/folders/kk/y3f49kbs3ps6rm04gb6qktv00000gn/T/pip-build-8i5itbya/qifqif/setup.py", line 36, in coerce_file
        stdout=subprocess.PIPE).communicate()
      File "/Users/Cedric/anaconda/envs/random_software/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/Users/Cedric/anaconda/envs/random_software/lib/python3.6/subprocess.py", line 1326, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'pandoc'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kk/y3f49kbs3ps6rm04gb6qktv00000gn/T/pip-build-8i5itbya/qifqif/
```

Does it mean that I need pandoc to use qifqif?

**Comment by Kraymer** [comment]
Well, it means that, but no you don't need id (pandoc is used to reformat the description of the module on pypi qifqif page).
Messup on my side : I will repackage it and ship a 0.7.2

**Comment by jerome-tgl** [comment]
**OS**: macOs 10.13.2
**CLI**: Termibal
**Software**: Python 2.7 | pip 9.0.1
**Install process**: pip install qifqif
**error log**:
```
Collecting qifqif
Collecting qifqif
  Using cached qifqif-0.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3l/qsr01z6j21534537d84chwcr0000gp/T/pip-build-ucYNfK/qifqif/setup.py", line 43, in <module>
        long_description=coerce_file('README.md'),
      File "/private/var/folders/3l/qsr01z6j21534537d84chwcr0000gp/T/pip-build-ucYNfK/qifqif/setup.py", line 36, in coerce_file
        stdout=subprocess.PIPE).communicate()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 20] Not a directory

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3l/qsr01z6j21534537d84chwcr0000gp/T/pip-build-ucYNfK/qifqif/
```

This error seems similar. Any solution/workaround?

**Comment by Kraymer** [comment]
I just reuploaded a fix.
Please `pip install qifqif` again

**Comment by Kraymer** [comment]
Closing the issue, feel free to reopen if still problems to install.
