### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by belidzs** [Kraymer/qifqif#82]
hi! I have faced the following:

```
C:\Users\belidzs>python -m pip install qifqif
Collecting qifqif
  Using cached https://files.pythonhosted.org/packages/09/43/848c8d8b4bcf1dcd1c54dd28a62935924ad4b7902e779e294710291537e7/qifqif-0.7.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\belidzs\AppData\Local\Temp\pip-install-lmebv90e\qifqif\setup.py", line 46, in <module>
        long_description=coerce_file('README.md'),
      File "C:\Users\belidzs\AppData\Local\Temp\pip-install-lmebv90e\qifqif\setup.py", line 18, in coerce_file
        text = open(os.path.join(os.path.dirname(__file__), fn)).read()
      File "C:\Program Files\Python35\lib\encodings\cp1250.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x83 in position 664: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\belidzs\AppData\Local\Temp\pip-install-lmebv90e\qifqif\
```

Environment:
```
C:\Users\belidzs>python --version
Python 3.5.2

C:\Users\belidzs>python -m pip --version
pip 19.0.3 from C:\Users\belidzs\AppData\Roaming\Python\Python35\site-packages\pip (python 3.5)
```

Am I doing something wrong?

**Comment by ebridges** [comment]
As it happens this project has not been upgraded to be compatible with Python 3.

It will, however, still work with Python 2.7.

If you're familiar with using Python Virtualenvs, you can create a virtualenv at Python 2.7 and use it that way.

Here's more info if you need it:
https://realpython.com/python-virtual-environments-a-primer/
